"""Initial migration

Revision ID: 1eab8b98da05
Revises: 
Create Date: 2021-09-06 10:34:25.711658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eab8b98da05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('website_url', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('profile_summary', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_summary')
    op.drop_column('user', 'website_url')
    # ### end Alembic commands ###

